categories:
  - 상의
  - 하의
  - 아우터
  - 원피스

sleeve:
  - 민소매
  - 반팔
  - 7부
  - 긴팔

collar:
  - 라운드
  - 브이넥
  - 셔츠카라
  - 세일러
  - 차이나

pocket:
  - 없음
  - 한쪽
  - 양쪽
  - 플랩포켓

color:
  - 블랙
  - 화이트
  - 네이비
  - 베이지
  - 레드
  - 그린

fabric:
  - 면
  - 울
  - 데님
  - 린넨
  - 가죽
  - 폴리
